//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metroit.Win.GcSpread.CodeDesign.Test {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleRex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleRex() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metroit.Win.GcSpread.CodeDesign.Test.SampleRex", typeof(SampleRex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  // 列ヘッダーの設定
        ///  &quot;ColumnHeader&quot;: {
        ///    // HorizontalAlignment, VerticalAlignment を指定すると、Columnsより強い
        ///    &quot;Rows&quot;: [
        ///      {
        ///        &quot;BaseTemplate&quot;: &quot;DefaultRow&quot;
        ///      },
        ///      {
        ///        &quot;Height&quot;: 20,
        ///        &quot;HorizontalAlignment&quot;: &quot;Left&quot;,
        ///        &quot;VerticalAlignment&quot;: &quot;Bottom&quot;
        ///      }
        ///    ],
        ///    &quot;Cells&quot;: [
        ///      [
        ///        {
        ///          &quot;Value&quot;: &quot;タイトル3&quot;,
        ///          &quot;HorizontalAlignment&quot;: &quot;Right&quot;,
        ///          &quot;VerticalAlignment&quot;: &quot;Top&quot;
        ///        },
        ///        {
        ///          &quot;BaseTemplate&quot;: &quot;DefaultCell [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleJson {
            get {
                return ResourceManager.GetString("SampleJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;ColumnHeader&quot;: {
        ///    &quot;Rows&quot;: [
        ///      {
        ///        &quot;TemplateName&quot;: &quot;DefaultRow&quot;,
        ///        &quot;Height&quot;: 40,
        ///        &quot;HorizontalAlignment&quot;: &quot;Right&quot;,
        ///        &quot;VerticalAlignment&quot;: &quot;Bottom&quot;
        ///      }
        ///    ],
        ///    &quot;Cells&quot;: [
        ///      {
        ///        &quot;TemplateName&quot;: &quot;DefaultCell&quot;,
        ///        &quot;Value&quot;: &quot;タイトル6&quot;,
        ///        &quot;HorizontalAlignment&quot;: &quot;Left&quot;,
        ///        &quot;VerticalAlignment&quot;: &quot;Bottom&quot;
        ///      }
        ///    ]
        ///  },
        ///  // 列の設定
        ///  &quot;Columns&quot;: [
        ///    {
        ///      &quot;TemplateName&quot;: &quot;BaseNumberTemplate&quot;,
        ///      &quot;HorizontalAlignment&quot;: &quot;Rig [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
